# Generated by Django 3.0.6 on 2021-01-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club'),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
