# Generated by Django 3.0.6 on 2021-01-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('account', '0003_auto_20210125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club'),
        ),
    ]
