# Generated by Django 3.0.6 on 2021-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210125_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
