# Generated by Django 3.0.6 on 2021-01-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=500)),
                ('history', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='players.Player')),
            ],
        ),
    ]
