# Generated by Django 3.0.6 on 2021-01-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='name',
            new_name='player_id',
        ),
    ]
