# Generated by Django 3.0.6 on 2021-01-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210122_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='player_id',
        ),
    ]
