# Generated by Django 3.0.6 on 2021-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_assessment_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='player_id',
            field=models.IntegerField(default=None),
        ),
    ]
