# Generated by Django 3.0.6 on 2021-01-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('assessment', '0006_auto_20210122_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='player_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
