# Generated by Django 3.0.6 on 2021-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20210122_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='player_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='surname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
