# Generated by Django 3.0.6 on 2021-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20210122_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='intensity',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='assessment',
            name='location',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration',
            field=models.TextField(max_length=500),
        ),
    ]
