# Generated by Django 3.0.6 on 2021-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20210122_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='findings',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='assessment',
            name='view',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='assessment',
            name='x_ray',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
