# Generated by Django 3.0.6 on 2021-01-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20210122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='scar',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='skin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='spasm',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='swelling',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tenderness_grade',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
