# Generated by Django 3.0.6 on 2021-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20210123_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='joint',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='rom',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
