# Generated by Django 3.0.6 on 2021-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20210123_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mrc_grade',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='muscle_group',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
