# Generated by Django 3.0.6 on 2021-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_auto_20210123_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='end_feel',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='types',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
