# Generated by Django 3.0.6 on 2021-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20210123_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='reflex_condition',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reflex_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
