# Generated by Django 3.0.6 on 2021-01-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_auto_20210123_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
