# Generated by Django 3.0.6 on 2021-02-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_assessment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='intensity',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
