# Generated by Django 3.0.6 on 2021-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_auto_20210209_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='location',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='view',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='x_ray',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
