# Generated by Django 3.0.6 on 2021-02-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0008_auto_20210207_1202'),
        ('assessment', '0020_auto_20210209_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='injuries.Injuries'),
        ),
    ]
