# Generated by Django 3.0.6 on 2021-02-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0008_auto_20210207_1202'),
        ('assessment', '0022_auto_20210224_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='injury',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='injuries.Injuries'),
        ),
    ]
