# Generated by Django 3.0.6 on 2021-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_auto_20210224_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='injury',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
