# Generated by Django 3.0.6 on 2021-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyparts', '0001_initial'),
        ('assessment', '0030_auto_20210303_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='injured_body_parts',
        ),
        migrations.AddField(
            model_name='assessment',
            name='injured_body_parts',
            field=models.ManyToManyField(to='bodyparts.BodyParts'),
        ),
    ]
