# Generated by Django 3.0.6 on 2021-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_auto_20210303_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='injured_body_parts',
        ),
        migrations.AddField(
            model_name='assessment',
            name='injured_body_parts',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
