# Generated by Django 3.0.6 on 2021-03-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injurytype', '0001_initial'),
        ('assessment', '0033_auto_20210303_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_type',
            field=models.ManyToManyField(to='injurytype.InjuryType'),
        ),
    ]
