# Generated by Django 3.0.6 on 2021-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_assessment_injury_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='other_injury',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
