# Generated by Django 3.0.6 on 2021-03-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0035_assessment_other_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='author',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
