# Generated by Django 3.0.6 on 2021-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_assessment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='diagnosis',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
