# Generated by Django 3.0.6 on 2021-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryco', '0001_initial'),
        ('assessment', '0037_assessment_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injuryco',
            field=models.ManyToManyField(to='injuryco.InjuryCo'),
        ),
    ]
