# Generated by Django 3.0.6 on 2021-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injurycause', '0001_initial'),
        ('assessment', '0038_assessment_injuryco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='injuryco',
        ),
        migrations.AddField(
            model_name='assessment',
            name='injury_cause',
            field=models.ManyToManyField(to='injurycause.InjuryCause'),
        ),
    ]
