# Generated by Django 3.0.6 on 2021-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryoccur', '0001_initial'),
        ('assessment', '0039_auto_20210304_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_occur',
            field=models.ManyToManyField(to='injuryoccur.InjuryOccur'),
        ),
    ]
