# Generated by Django 3.0.6 on 2021-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryco', '0001_initial'),
        ('assessment', '0040_assessment_injury_occur'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_co',
            field=models.ManyToManyField(to='injuryco.InjuryCo'),
        ),
    ]
