# Generated by Django 3.0.6 on 2021-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryviolation', '0001_initial'),
        ('assessment', '0041_assessment_injury_co'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_violation',
            field=models.ManyToManyField(to='injuryviolation.InjuryViolation'),
        ),
    ]
