# Generated by Django 3.0.6 on 2021-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advicegiven', '0001_initial'),
        ('assessment', '0042_assessment_injury_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='advice_given',
            field=models.ManyToManyField(to='advicegiven.AdviceGiven'),
        ),
    ]
