# Generated by Django 3.0.6 on 2021-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('severity', '0001_initial'),
        ('assessment', '0043_assessment_advice_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='severity',
            field=models.ManyToManyField(to='severity.Severity'),
        ),
    ]
