# Generated by Django 3.0.6 on 2021-03-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actiontaken', '0001_initial'),
        ('assessment', '0044_assessment_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='action_taken',
            field=models.ManyToManyField(to='actiontaken.ActionTaken'),
        ),
    ]
