# Generated by Django 3.0.6 on 2021-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryprevious', '0001_initial'),
        ('assessment', '0045_assessment_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='previous_injury',
            field=models.ManyToManyField(to='injuryprevious.InjuryPrevious'),
        ),
    ]
