# Generated by Django 3.0.6 on 2021-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuryprevious', '0001_initial'),
        ('assessment', '0046_assessment_previous_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='previous_injury',
        ),
        migrations.AddField(
            model_name='assessment',
            name='injury_previous',
            field=models.ManyToManyField(to='injuryprevious.InjuryPrevious'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='other_collision',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
