# Generated by Django 3.0.6 on 2021-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refereesanction', '0001_initial'),
        ('assessment', '0047_auto_20210304_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='referee_sanction',
            field=models.ManyToManyField(to='refereesanction.RefereeSanction'),
        ),
    ]
