# Generated by Django 3.0.6 on 2021-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0048_assessment_referee_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_occur_other',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
