# Generated by Django 3.0.6 on 2021-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0049_assessment_injury_occur_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='other_advice_given',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
