# Generated by Django 3.0.6 on 2021-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
        ('assessment', '0050_assessment_other_advice_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='other_referral',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='referral',
            field=models.ManyToManyField(to='referral.Referral'),
        ),
    ]
