# Generated by Django 3.0.6 on 2021-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protective_equipment', '0001_initial'),
        ('assessment', '0051_auto_20210305_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='other_protective_equipment',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='protective_equipment',
            field=models.ManyToManyField(to='protective_equipment.ProtectiveEquipment'),
        ),
    ]
