# Generated by Django 3.0.6 on 2021-01-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('severity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injuries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('symptoms', models.TextField(max_length=500)),
                ('diagnostic_tests', models.TextField(max_length=500)),
                ('healing', models.TextField(max_length=500)),
                ('complications', models.TextField(max_length=500)),
                ('treatment', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slug', models.SlugField(default=None, unique=True)),
                ('classification', models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='severity.Severity')),
            ],
        ),
    ]
