# Generated by Django 3.0.6 on 2021-02-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0003_auto_20210206_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuries',
            name='description',
            field=models.TextField(),
        ),
    ]
