# Generated by Django 3.0.6 on 2021-02-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0005_auto_20210206_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuries',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
