# Generated by Django 3.0.6 on 2021-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0006_auto_20210206_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuries',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
