# Generated by Django 3.0.6 on 2021-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0007_auto_20210207_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuries',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
