# Generated by Django 3.0.6 on 2021-02-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_auto_20210205_1551'),
        ('season', '0002_auto_20210223_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_club_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=None, null=True)),
                ('assists', models.PositiveIntegerField(default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club')),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='players.Player')),
                ('season', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='season.Season')),
            ],
        ),
    ]
