# Generated by Django 3.0.6 on 2021-03-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injuryactivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InjuryCo',
            new_name='InjuryActivity',
        ),
    ]
