# Generated by Django 3.0.6 on 2021-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_auto_20210205_1551'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='players.Player')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='status.Status')),
            ],
        ),
    ]
