# Generated by Django 3.0.6 on 2021-02-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='starts_on',
            new_name='started_on',
        ),
    ]
