# Generated by Django 3.0.6 on 2021-02-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_leagues_image'),
        ('clubs', '0003_club_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='leagues.Leagues'),
        ),
    ]
