# Generated by Django 3.0.6 on 2021-03-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0004_auto_20210225_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=None, max_length=100, null=True)),
                ('club_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club')),
            ],
        ),
    ]
