# Generated by Django 3.0.6 on 2021-02-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='countries.Countries'),
        ),
    ]
