# Generated by Django 3.0.6 on 2021-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_leagues_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
