# Generated by Django 3.0.6 on 2021-01-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('clubs', '0001_initial'),
        ('position', '0001_initial'),
        ('foot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nationality', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=200)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('age', models.PositiveIntegerField(default=None, null=True)),
                ('height', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('jersey_number', models.PositiveIntegerField(default=None, null=True)),
                ('strengths', models.CharField(default=None, max_length=100)),
                ('weaknesses', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slug', models.SlugField(default=None, unique=True)),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club')),
                ('position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='position.Position')),
                ('preferred_foot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='foot.Foot')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='status.Status')),
            ],
        ),
    ]
