# Generated by Django 3.0.6 on 2021-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
